language: r

sudo: required
cache: packages
bioc_required: true
warnings_are_errors: true

r:
 - release
 - devel

apt_packages:
 - libnetcdf-dev
 - udunits-bin
 - libudunits2-dev
 - netcdf-bin
 - libopenbabel-dev

bioc_packages:
    - mzR

r_github_packages:
    - thomasp85/patchwork
    - jasenfinch/binneR
    - jasenfinch/metabolyseR
    - jasenfinch/mzAnnotation
    - jasenfinch/MFassign
    - jasenfinch/profilePro
    - jasenfinch/metaboMisc

notifications:
    email:
    on_success: change
    on_failure: change